import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider, ThemeProvider } from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <body className="antialiased">{children}</body>
        </ThemeProvider>
      </AuthProvider>
    </html>
  );
}
